grid: 
  size: 50
  types:
    '`': top  
    ',': free
    'o': cloud
    'B': brick
    '=': floor
    'X': ground
  content: |-
    ````````````````````````
    ,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,o,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,B,,,,
    ,,,,,=====,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,
    ========================
    XXXXXXXXXXXXXXXXXXXXXXXX