grid: 
  size: 50
  types:
    'A': plain
    'B': swamp
    'C': mountain
  content: |-
    AAAAAAAAAAAA
    ABAAAAAAAAAA
    AACAAAAAAAAA
    AAAAAAAAAAAA
    AAAAAAAAAAAA
    AAAAAAAAAAAA
    AAAAAAAAAAAA
    AAAAAAAAABAA
    AAAAAAAAAAAA