grid: 
  size: 50
  types:
    '`': top  
    ',': free
    'o': cloud
    'B': brick
    '=': floor
    'X': ground
  content: |-
    ````````````````````````
    X,,,,,,,,,,,,,,,,,,,,,,X
    X,,,,,o,,,,,,,,,,,,,,,,X
    X,,,,,,,,,,,,,,,,,,,,,,X
    X,,,,,,,,,,,,,,,,,,B,,,X
    X,,,,=====,,,,,,,,,,,,,X
    X,,,,,,,,,,,,,,,,,,,,,,X
    X,,,,,,,,,,,,,,,,,,,,,,X
    X,,,,,,,,,,,,,,,,,,,,,,X
    ========================
    XXXXXXXXXXXXXXXXXXXXXXXX