tile_types:
  free:
    sprite: sheet:0:0
    movement: 1
  top:
    sprite: sheet:0:0
    movement: 1
  floor: 
    sprite: sheet:1:0
    movement: 0
  ground: 
    sprite: sheet:1:0
    movement: 0
  cloud: 
    sprite: sheet:1:0
    movement: 0
  brick: 
    sprite: sheet:1:0
    movement: 0
  