tile_types:
  free:
    sprite: sheet:0:0
    movement: 1
    collide: false
  top:
    sprite: sheet:1:0
    movement: 1
    collide: true
  floor: 
    sprite: sheet:1:0
    movement: 0
    collide: true
  ground: 
    sprite: sheet:1:0
    movement: 0
    collide: true
  cloud: 
    sprite: sheet:2:0
    movement: 0
    collide: false
  brick: 
    sprite: sheet:1:0
    movement: 0
    collide: true
  