sheets:
  - label: sheet
    path: sheet.png
    rect: 
      x: 100
      y: 100
    sizes:
      - 100
      - 50
  - label: morris
    path: morris.png
    rect: 
      x: 1024
      y: 1024
    sizes: 
      - 512
  - label: ball
    path: ball.png
    rect: 
      x: 512
      y: 512
    sizes: 
      - 512
