mobs: 
  arthur:
    type: Mob
    states: bomber
    sprite: 
      path: morris
      size: 100
    position: 
      x: 200
      'y': 100
  dummy:
    type: Mob
    states: goon 
    sprite: 
      path: morris
      size: 200
    position: 
      x: 600
      'y': 200
    