l10n:
  fr:
    data:
      error_message: Que voulez-vous dire par "%s" ?
      you_are: Vous êtes
      you_see: Vous voyez
      inside_office_building: dans un immeuble de bureau
      door_behind: Il y a une porte derrière vous
      leading_outside: menant à l'extérieur
      nothing: rien
      key: une clé
      orange: une orange
      door_seems: La porte semble être
      door_locked: verrouillée
      door_unlocked: déverrouillée
      door_open: ouverte
