imports:
  - fr
templates:
  frame: |-
    {{ define "header" }}------------------------------
    {{ end }}
    {{ define "footer" }}{{if .Feedback}}
      {{.Feedback}}{{end}}{{if .Error}}
      {{ translate "error_message" .Error}}{{end}}
    {{ end }}  
  default: |
    {{ template "header" . }}
    {{ translate "you_are"}} {{translate "inside_office_building"}}.
    {{ translate "door_behind" }}, {{ translate "leading_outside"}}.
    {{translate "you_see"}} {{with .Default.Items}}{{range $i, $e := .}}{{if $i}}, {{end}}{{ translate $e }}{{end}}{{else}}{{translate "nothing"}}{{end}}.
    {{translate "door_seems"}} {{if .Default.DoorOpen}}{{translate "door_open"}}{{else if .Default.DoorUnlocked}}{{translate "door_unlocked"}}{{else}}{{translate "door_locked"}}{{end}}.

    {{ template "footer" . }}
  outside: |
    {{ template "header" . }}
    You are outisde the building.
    {{if .DoorOpen}}The door to the building behind you seems to be unlocked.{{else}}The door behind you seems to be locked.{{end}}
    {{ template "footer" . }}