imports:
  - l10n/en
  - l10n/fr
templates:
  frame: |-
    {{ define "header" }}------------------------------
    {{ end }}
    {{ define "footer" }}{{if .Feedback}}
      {{.Feedback}}{{end}}{{if .Error}}
      {{ translate "error_message" .Error}}{{end}}
    {{ end }}  
  default: |
    {{ template "header" . }}
    {{ translate "you_are"}} {{translate "inside_office_building"}}.
    {{ translate "door_behind" }}, {{ translate "leading_outside"}}.
    You see {{with .Default.Items}}{{range $i, $e := .}}{{if $i}}, {{end}}{{ $e }}{{end}}{{else}}nothing{{end}}.
    {{if .Default.DoorOpen}}The door is open.{{else if .Default.DoorUnlocked}}The door seems to be unlocked.{{else}}The door seems locked.{{end}}

    {{ template "footer" . }}
  outside: |
    {{ template "header" . }}
    You are outisde the building.
    {{if .DoorOpen}}The door to the building behind you seems to be unlocked.{{else}}The door behind you seems to be locked.{{end}}
    {{ template "footer" . }}