l10n:
  fr:
    data:
      error_message: "What do you mean exactly by"
      you_are: "Vous êtes"
      inside_office_building: "dans un immeuble de bureau"
      door_behind: "Il y a une porte derrière vous"
